/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TurnkeyRouteImport } from './routes/turnkey'
import { Route as SterilisationRouteImport } from './routes/sterilisation'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ImplantsRouteImport } from './routes/implants'
import { Route as HandpiecesRouteImport } from './routes/handpieces'
import { Route as DentalChairsRouteImport } from './routes/dental-chairs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const TurnkeyRoute = TurnkeyRouteImport.update({
  id: '/turnkey',
  path: '/turnkey',
  getParentRoute: () => rootRouteImport,
} as any)
const SterilisationRoute = SterilisationRouteImport.update({
  id: '/sterilisation',
  path: '/sterilisation',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ImplantsRoute = ImplantsRouteImport.update({
  id: '/implants',
  path: '/implants',
  getParentRoute: () => rootRouteImport,
} as any)
const HandpiecesRoute = HandpiecesRouteImport.update({
  id: '/handpieces',
  path: '/handpieces',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalChairsRoute = DentalChairsRouteImport.update({
  id: '/dental-chairs',
  path: '/dental-chairs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dental-chairs': typeof DentalChairsRoute
  '/handpieces': typeof HandpiecesRoute
  '/implants': typeof ImplantsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sterilisation': typeof SterilisationRoute
  '/turnkey': typeof TurnkeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dental-chairs': typeof DentalChairsRoute
  '/handpieces': typeof HandpiecesRoute
  '/implants': typeof ImplantsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sterilisation': typeof SterilisationRoute
  '/turnkey': typeof TurnkeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dental-chairs': typeof DentalChairsRoute
  '/handpieces': typeof HandpiecesRoute
  '/implants': typeof ImplantsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sterilisation': typeof SterilisationRoute
  '/turnkey': typeof TurnkeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/dental-chairs'
    | '/handpieces'
    | '/implants'
    | '/sitemap.xml'
    | '/sterilisation'
    | '/turnkey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/dental-chairs'
    | '/handpieces'
    | '/implants'
    | '/sitemap.xml'
    | '/sterilisation'
    | '/turnkey'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/dental-chairs'
    | '/handpieces'
    | '/implants'
    | '/sitemap.xml'
    | '/sterilisation'
    | '/turnkey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DentalChairsRoute: typeof DentalChairsRoute
  HandpiecesRoute: typeof HandpiecesRoute
  ImplantsRoute: typeof ImplantsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SterilisationRoute: typeof SterilisationRoute
  TurnkeyRoute: typeof TurnkeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/turnkey': {
      id: '/turnkey'
      path: '/turnkey'
      fullPath: '/turnkey'
      preLoaderRoute: typeof TurnkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sterilisation': {
      id: '/sterilisation'
      path: '/sterilisation'
      fullPath: '/sterilisation'
      preLoaderRoute: typeof SterilisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/implants': {
      id: '/implants'
      path: '/implants'
      fullPath: '/implants'
      preLoaderRoute: typeof ImplantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handpieces': {
      id: '/handpieces'
      path: '/handpieces'
      fullPath: '/handpieces'
      preLoaderRoute: typeof HandpiecesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-chairs': {
      id: '/dental-chairs'
      path: '/dental-chairs'
      fullPath: '/dental-chairs'
      preLoaderRoute: typeof DentalChairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DentalChairsRoute: DentalChairsRoute,
  HandpiecesRoute: HandpiecesRoute,
  ImplantsRoute: ImplantsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SterilisationRoute: SterilisationRoute,
  TurnkeyRoute: TurnkeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
