/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TurnkeyRouteImport } from './routes/turnkey'
import { Route as SterilisationRouteImport } from './routes/sterilisation'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ImplantsRouteImport } from './routes/implants'
import { Route as HandpiecesRouteImport } from './routes/handpieces'
import { Route as DentalChairsRouteImport } from './routes/dental-chairs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProductsCategoryRouteImport } from './routes/products.$category'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as ProductsCategoryProductRouteImport } from './routes/products.$category.$product'
import { Route as AdminProductsIdRouteImport } from './routes/admin/products.$id'

const TurnkeyRoute = TurnkeyRouteImport.update({
  id: '/turnkey',
  path: '/turnkey',
  getParentRoute: () => rootRouteImport,
} as any)
const SterilisationRoute = SterilisationRouteImport.update({
  id: '/sterilisation',
  path: '/sterilisation',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ImplantsRoute = ImplantsRouteImport.update({
  id: '/implants',
  path: '/implants',
  getParentRoute: () => rootRouteImport,
} as any)
const HandpiecesRoute = HandpiecesRouteImport.update({
  id: '/handpieces',
  path: '/handpieces',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalChairsRoute = DentalChairsRouteImport.update({
  id: '/dental-chairs',
  path: '/dental-chairs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductsCategoryRoute = ProductsCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => ProductsRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const ProductsCategoryProductRoute = ProductsCategoryProductRouteImport.update({
  id: '/$product',
  path: '/$product',
  getParentRoute: () => ProductsCategoryRoute,
} as any)
const AdminProductsIdRoute = AdminProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/brands': typeof BrandsRoute
  '/contact': typeof ContactRoute
  '/dental-chairs': typeof DentalChairsRoute
  '/handpieces': typeof HandpiecesRoute
  '/implants': typeof ImplantsRoute
  '/products': typeof ProductsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sterilisation': typeof SterilisationRoute
  '/turnkey': typeof TurnkeyRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/products/$category': typeof ProductsCategoryRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/products/$category/$product': typeof ProductsCategoryProductRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brands': typeof BrandsRoute
  '/contact': typeof ContactRoute
  '/dental-chairs': typeof DentalChairsRoute
  '/handpieces': typeof HandpiecesRoute
  '/implants': typeof ImplantsRoute
  '/products': typeof ProductsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sterilisation': typeof SterilisationRoute
  '/turnkey': typeof TurnkeyRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/products/$category': typeof ProductsCategoryRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/products/$category/$product': typeof ProductsCategoryProductRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/brands': typeof BrandsRoute
  '/contact': typeof ContactRoute
  '/dental-chairs': typeof DentalChairsRoute
  '/handpieces': typeof HandpiecesRoute
  '/implants': typeof ImplantsRoute
  '/products': typeof ProductsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sterilisation': typeof SterilisationRoute
  '/turnkey': typeof TurnkeyRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/products/$category': typeof ProductsCategoryRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/products/$category/$product': typeof ProductsCategoryProductRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/brands'
    | '/contact'
    | '/dental-chairs'
    | '/handpieces'
    | '/implants'
    | '/products'
    | '/sitemap.xml'
    | '/sterilisation'
    | '/turnkey'
    | '/admin/categories'
    | '/admin/login'
    | '/admin/products'
    | '/products/$category'
    | '/admin/'
    | '/admin/products/$id'
    | '/products/$category/$product'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brands'
    | '/contact'
    | '/dental-chairs'
    | '/handpieces'
    | '/implants'
    | '/products'
    | '/sitemap.xml'
    | '/sterilisation'
    | '/turnkey'
    | '/admin/categories'
    | '/admin/login'
    | '/admin/products'
    | '/products/$category'
    | '/admin'
    | '/admin/products/$id'
    | '/products/$category/$product'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/brands'
    | '/contact'
    | '/dental-chairs'
    | '/handpieces'
    | '/implants'
    | '/products'
    | '/sitemap.xml'
    | '/sterilisation'
    | '/turnkey'
    | '/admin/categories'
    | '/admin/login'
    | '/admin/products'
    | '/products/$category'
    | '/admin/'
    | '/admin/products/$id'
    | '/products/$category/$product'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BrandsRoute: typeof BrandsRoute
  ContactRoute: typeof ContactRoute
  DentalChairsRoute: typeof DentalChairsRoute
  HandpiecesRoute: typeof HandpiecesRoute
  ImplantsRoute: typeof ImplantsRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SterilisationRoute: typeof SterilisationRoute
  TurnkeyRoute: typeof TurnkeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/turnkey': {
      id: '/turnkey'
      path: '/turnkey'
      fullPath: '/turnkey'
      preLoaderRoute: typeof TurnkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sterilisation': {
      id: '/sterilisation'
      path: '/sterilisation'
      fullPath: '/sterilisation'
      preLoaderRoute: typeof SterilisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/implants': {
      id: '/implants'
      path: '/implants'
      fullPath: '/implants'
      preLoaderRoute: typeof ImplantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handpieces': {
      id: '/handpieces'
      path: '/handpieces'
      fullPath: '/handpieces'
      preLoaderRoute: typeof HandpiecesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-chairs': {
      id: '/dental-chairs'
      path: '/dental-chairs'
      fullPath: '/dental-chairs'
      preLoaderRoute: typeof DentalChairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/products/$category': {
      id: '/products/$category'
      path: '/$category'
      fullPath: '/products/$category'
      preLoaderRoute: typeof ProductsCategoryRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/products/$category/$product': {
      id: '/products/$category/$product'
      path: '/$product'
      fullPath: '/products/$category/$product'
      preLoaderRoute: typeof ProductsCategoryProductRouteImport
      parentRoute: typeof ProductsCategoryRoute
    }
    '/admin/products/$id': {
      id: '/admin/products/$id'
      path: '/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminProductsIdRouteImport
      parentRoute: typeof AdminProductsRoute
    }
  }
}

interface AdminProductsRouteChildren {
  AdminProductsIdRoute: typeof AdminProductsIdRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsIdRoute: AdminProductsIdRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProductsCategoryRouteChildren {
  ProductsCategoryProductRoute: typeof ProductsCategoryProductRoute
}

const ProductsCategoryRouteChildren: ProductsCategoryRouteChildren = {
  ProductsCategoryProductRoute: ProductsCategoryProductRoute,
}

const ProductsCategoryRouteWithChildren =
  ProductsCategoryRoute._addFileChildren(ProductsCategoryRouteChildren)

interface ProductsRouteChildren {
  ProductsCategoryRoute: typeof ProductsCategoryRouteWithChildren
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsCategoryRoute: ProductsCategoryRouteWithChildren,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BrandsRoute: BrandsRoute,
  ContactRoute: ContactRoute,
  DentalChairsRoute: DentalChairsRoute,
  HandpiecesRoute: HandpiecesRoute,
  ImplantsRoute: ImplantsRoute,
  ProductsRoute: ProductsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SterilisationRoute: SterilisationRoute,
  TurnkeyRoute: TurnkeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
