/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DentalChairsRouteImport } from './routes/dental-chairs'
import { Route as IndexRouteImport } from './routes/index'

const DentalChairsRoute = DentalChairsRouteImport.update({
  id: '/dental-chairs',
  path: '/dental-chairs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dental-chairs': typeof DentalChairsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dental-chairs': typeof DentalChairsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dental-chairs': typeof DentalChairsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dental-chairs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dental-chairs'
  id: '__root__' | '/' | '/dental-chairs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DentalChairsRoute: typeof DentalChairsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dental-chairs': {
      id: '/dental-chairs'
      path: '/dental-chairs'
      fullPath: '/dental-chairs'
      preLoaderRoute: typeof DentalChairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DentalChairsRoute: DentalChairsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
